class TicTacToeProject{
    
    public static void main(String[] args){
        // System.out.println("Nightwing Wears Blue");
        // boolean ThomasIsCool = true;
        // System.out.println(ThomasIsCool);
        // int peepeesize = 2;
        // System.out.println(peepeesize);
        // peepeesize += 1;
        // System.out.println(peepeesize);
        // peepeesize -= 1;
        // System.out.println(peepeesize);
        // String fastCar = "it is really fast";
        // System.out.println(fastCar);
        // fastCar += " but ugly asf";
        // System.out.println(fastCar);
        // fastCar = fastCar.substring(0, 10);
        // System.out.println(fastCar);
        // int[] numbers = {1, 2, 3, 4, 5};
        // System.out.println(numbers);
        // while(true){
        //     for (int i = 0; i < numbers.length; i++){
        //         System.out.println(numbers[i]);
        //     }
        // }
        int a = 3;
        int b = 4;
        if (a== 4){
            System.out.println("something went wrong");
        } else{
            System.out.println("nothing went wrong");
        }
        if (b == 3){
            System.out.println("nothing went wrong");
        } else if (b > 3) {
            System.out.println("b is less than 3");
        } else if (b < 3) {
            System.out.println("b is less than 3");
        }

    }

}